import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Itim } from 'next/font/google'
import { FC, PropsWithChildren } from 'react'

const font = Itim({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Simple Next.js',
  description: 'Generated by Simple Next.js',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => (
  <html lang="en">
    <body className={font.className}>
      {children}
    </body>
  </html>
)

export default RootLayout
